### ISSUE TITLE
Content thumbnail shows channel logo

### ISSUE THREAD

**Issue by jake404** [fHDHR/fHDHR_plugin_origin_tvheadend#13]
TVHeadend shows a program poster image in the EPG. This image comes from the XMLTV source I'm using. Isn't fHDHR supposed to retrieve that image and show it as a content thumbnail in the guide? I only get the channel logo in that column. 

![image](https://user-images.githubusercontent.com/12189899/125165191-32e2cb00-e196-11eb-9b94-b0c419901474.png)

![image](https://user-images.githubusercontent.com/12189899/125165157-1050b200-e196-11eb-9bf3-d5a5413b6cda.png)

**Comment by deathbybandaid** [comment]
It's supposed to. The channel logo is a cheap method of error handling for when it's not grabbed from the api properly.

I'll try to take a look in the next few days.

**Comment by jake404** [comment]
Just want to keep this issue alive as the bot considered it to be stale.
