### ISSUE TITLE
Select streaming profile

### ISSUE THREAD

**Issue by admlko** [fHDHR/fHDHR_plugin_origin_tvheadend#14]
I was looking for an option to select tvheadend streaming profile.

In the plugin options, there is `stream_method` but when I look at the [code](https://github.com/fHDHR/fHDHR_plugin_origin_tvheadend/blob/8228a2e98e130bde2c88c111c3bcf28e344563df/origin/__init__.py#L16), I don't see it used anywhere (at least between fHDHR <-> tvheadend).

Also, what is the function of `origin_quality` ?
[I see](https://github.com/fHDHR/fHDHR_plugin_origin_tvheadend/blob/8228a2e98e130bde2c88c111c3bcf28e344563df/origin/__init__.py#L84) that is is always set to `pass` but that seems to be exactly what I am looking for.
So how could I set it properly?

**Comment by deathbybandaid** [comment]
`stream_method` can be set to "vlc" or "ffmpeg", if those plugins are installed.

`origin_quality` can be set to quality profiles from tvheadend. (at least that is the intention, I may have not finished writing the code for that tbh)
